### ISSUE TITLE
ERROR in unable to locate 'tinode-webapp/node_modules/tinode-sdk/umd/tinode.prod.js.map' glob

### ISSUE THREAD

**Issue by sun2008mt** [tinode/react-js#117]
**Describe the bug**
In branch master, error occurs when executing `npm run build:prod` or `npm run build:dev`.
But the build process finishes successfully in tag v0.20.4.

**To Reproduce**
1. git clones the source code
2. npm installs the dependent packages
3. execute `npm run build:prod`
4. See error: unable to locate 'tinode-webapp/node_modules/tinode-sdk/umd/tinode.prod.js.map'

**Expected behavior**
build process finishes successfully

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - TinodeWeb Version: 0.21.1

**Console log**
ERROR in unable to locate 'tinode-webapp/node_modules/tinode-sdk/umd/tinode.prod.js.map' glob

**Comment by or-else** [comment]
You probably building against the previous version of the sdk. We switched tinode-sdk build from browserify to webpack. The webpack generates the .map files while browserify does not. Make sure you are building with the latest SDK. Or you can just comment out this line: https://github.com/tinode/webapp/blob/master/webpack.config.js#L62

**Comment by sun2008mt** [comment]
Ok, commenting out that line solves the problem! The tinode-sdk version was checked as v0.21.1. I tried to clean the npm cache, and changed the npm registry to the official url, or even recloned the source code on a new computer. But if uncomment, the error still occurs.

**Comment by or-else** [comment]
try `npm link`.

**Comment by sun2008mt** [comment]
I will comment out that line, it works. I just wonder if I'm the only one facing this error.
I can't find the `*.map` file under the `umd` directory of `tinode-sdk` package. 
There are just `tinode.prod.js` and `tinode.dev.js` file.

**Comment by or-else** [comment]
Indeed `.map` files are missing from the published package. They are present when you build locally. 
I've added them to the publishing config and they will be present in the next published package:
https://github.com/tinode/tinode-js/commit/1144006d504d0cbc6979f1a87e8c00f850cb225d

**Comment by sun2008mt** [comment]
ok~

**Comment by or-else** [comment]
I believe this is resolved. Please reopen if not.
