### ISSUE TITLE
Image upload problem

### ISSUE THREAD

**Issue by pallid** [tinode/react-js#79]
**Describe the bug**
Image upload problem

**To Reproduce**
1. login to 'https://sandbox.tinode.co/'
2. Click on any topic
3. Click on upload image
4. Select image in explorer

**Expected behavior**
Loading a picture into a topic

**Screenshots**
https://recordit.co/muIscy1x6i screencast

**Environment (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Browser [Chrome]
 - TinodeWeb Version [0.17.3] may be 0.17.2

**Console log**
```
Uncaught (in promise) TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at index.prod.js:1
    at Image.l.onload (index.prod.js:1)
```

**Comment by or-else** [comment]
Fix released in https://github.com/tinode/webapp/releases/tag/v0.17.5
